name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    name: Testing ${{ matrix.PMM_tool }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        PMM_tool: ['cmcm', 'conan', 'vcpkg', 'pmm-cli']
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-python@v7

    - name: CMake
      working-directory:  tests/${{ matrix.PMM_tool }}
      run: cmake -DCMAKE_BUILD_TYPE=Release .

    - name: Build
      working-directory:  tests/${{ matrix.PMM_tool }}
      run: cmake --build . --config Release
